=== pablogalvezprojectosdaw/examen-UD4/pedidos.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT pedidos (pedido)*>
<!ELEMENT pedido (sucursal)*>
<!ELEMENT sucursal (ubicacion|direccion|trabajador|fecha|observaciones|articulos)*>
<!ATTLIST sucursal
    codigo CDATA #IMPLIED>
<!ELEMENT ubicacion (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT trabajador (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT articulos (articulo)*>
<!ELEMENT articulo (unidades|precio|observaciones|plazo)*>
<!ATTLIST articulo
    codigo CDATA #IMPLIED>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== pablogalvezprojectosdaw/examen-UD4/pedidos_DTD.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE pedidos SYSTEM "pedidos.dtd">

<pedidos>
    <pedido>
        <sucursal codigo = "A1234567">
            <ubicacion>Ubrique</ubicacion>
            <direccion>C/ Pabajo 7</direccion>
            <trabajador>Juan Perez</trabajador>
            <fecha>14/11/2020</fecha>
            <observaciones>urgente</observaciones>
            <articulos>
                <articulo codigo = "AAA-111">
                    <unidades>1</unidades>
                    <precio>20</precio>
                    <observaciones>"Inserte observacion"</observaciones>
                    <plazo>20</plazo>
                    </articulo>
             </articulos>
        </sucursal>
    </pedido>
</pedidos>
