=== pablogalvezprojectosdaw/examen-UD4/pedidosSchema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="pedidos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pedido">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sucursal">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="ubicacion"/>
                    <xs:element type="xs:string" name="direccion"/>
                    <xs:element type="xs:string" name="trabajador"/>
                    <xs:element type="xs:date" name="fecha"/>
                    <xs:element type="xs:string" name="observaciones"/>
                    <xs:element name="articulos">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="articulo">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element type="xs:byte" name="unidades"/>
                                <xs:element type="xs:byte" name="precio"/>
                                <xs:element type="xs:string" name="observaciones"/>
                                <xs:element type="xs:byte" name="plazo"/>
                              </xs:sequence>
                              <xs:attribute type="xs:string" name="codigo"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="codigo"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pablogalvezprojectosdaw/examen-UD4/pedidos_XSD.xml
<?xml version="1.0" encoding="ISO-8859-1"?>


<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pedidosSchema.xsd">
    <pedido>
        <sucursal codigo = "A1234567">
            <ubicacion>Ubrique</ubicacion>
            <direccion>C/ Pabajo 7</direccion>
            <trabajador>Juan Perez</trabajador>
            <fecha>2020-11-14</fecha>
            <observaciones>urgente</observaciones>
            <articulos>
                <articulo codigo = "AAA-111">
                    <unidades>1</unidades>
                    <precio>20</precio>
                    <observaciones>"Inserte observacion"</observaciones>
                    <plazo>20</plazo>
                    </articulo>
             </articulos>
        </sucursal>
    </pedido>
</pedidos>
